pipeline {
    agent any

    environment {
        // Use the credentials ID you set in Jenkins
        GIT_CREDENTIALS = credentials('github-creds')
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: "${GIT_CREDENTIALS}", url: 'https://github.com/Muliro1/alx-backend-python.git', branch: 'main'
            }
        }
        stage('Show Git Branch') {
            steps {
                sh 'git branch'
            }
        }
        stage('Install dependencies') {
            steps {
                withPythonEnv('python3') {
                    sh 'pip3 install --upgrade pip'
                    sh 'pip3 install -r messaging_app/requirements.txt'
                }
            }
        }
        stage('Run Tests') {
            steps {
                withPythonEnv('python3') {
                    sh 'pytest --junitxml=report.xml'
                }
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("yourdockerhubusername/messaging_app:${env.BUILD_NUMBER}")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-creds') {
                        dockerImage.push()
                    }
                }
            }
        }
    }
    triggers {
        // No triggers for manual only
    }
}
