apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
      - name: messaging-app
        image: messaging_app:2.0
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: messaging-app-config
        - secretRef:
            name: messaging-app-secrets



